site_name: Azeem Jiva
site_url: https://www.javawithjiva.com/
site_description: Azeem's personal website - Java with Jiva
site_author: Azeem Jiva

theme:
  name: material
  font:
    text: Roboto
    code: B612 Mono
  palette:
    scheme: default
     # Palette toggle for automatic mode
    media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode

    # Palette toggle for light mode
    media: "(prefers-color-scheme: light)"
      scheme: default 

    toggle:
      icon: lucide/sun
      name: Switch to dark mode

    # Palette toggle for dark mode
    media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to system preference
  logo: assets/images/favicon.png
  features:
    - search.highlight
  
copyright: Copyright &copy; 2025 Azeem Jiva

plugins:
  - social:
      cards_font: Roboto
  - minify:
      minify_html: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/javawithjiva/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/azeemjiva/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@Javawithjiva
