[project]
site_name = "Azeem Jiva"
site_url = "https://www.javawithjiva.com/"
site_description = "Azeem's personal website - Java with Jiva"
site_author = "Azeem Jiva"
copyright = "Copyright &copy; 2025 Azeem Jiva"

[project.theme]
scheme = "slate"
variant = "modern"
language = "en"
font.text = "Roboto"
font.code = "JetBrains Mono"
favicon = "assets/images/favicon.png"
logo = "assets/images/favicon.png"

[project.extra]
generator = false
  
[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/azeemjiva/"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/azeemjiva"
